name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - name: Use Node
        uses: actions/setup-node@v4
        with: { node-version: 20, cache: "pnpm" }
      - run: pnpm i --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: E2E
        run: pnpm test:e2e
      - name: Lighthouse
        run: pnpm lighthouse:ci
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
