name: Database Health Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  database-health:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run database health check
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: node scripts/database-health-monitor.js
      
    - name: Run pre-deployment validation
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      run: node scripts/pre-deployment-check.js
      
    - name: Test build
      run: npm run build
      
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Database health check failed!"
        echo "🚫 Deployment blocked due to database inconsistencies"
        echo "🔧 Please fix the issues before deploying"
